---
name: learn-github-actions
on:
  - push
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: install apt dependencies
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: qemu-utils qemu-user-static binfmt-support kpartx u-boot-tools
          version: 1.0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: build the image
        env:
          DIB_RELEASE: focal
          # DIB_PYTHON_VERSION: 3
          OUTPUT_FILE: ubuntu.qcow2
          ARCH: amd64
          ELEMENTS_PATH: elements
          # LIBGUESTFS_BACKEND: direct
          # ELEMENTS: "vm block-device-efi dhcp-all-interfaces pip-and-virtualenv"
        run: |
          disk-image-create \
          vm \
          base \
          block-device-efi \
          ubuntu \
          -a $ARCH \
          -o $OUTPUT_FILE
