---
name: learn-github-actions
on:
  - push
jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      DIB_IMAGE_CACHE: /tmp/dib_cache
      DIB_RELEASE: focal
      DIB_CLOUD_INIT_DATASOURCES: OpenStack
      ELEMENTS_PATH: elements
      ARCH: amd64
      OUTPUT_FILE: ubuntu.qcow2
    steps:
      - uses: actions/checkout@v3
        name: install apt dependencies
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: qemu-utils qemu-user-static binfmt-support kpartx u-boot-tools
          version: 1.0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: cache DIB builds
        uses: actions/cache@v3
        with:
          path: ${{ env.DIB_IMAGE_CACHE }}
          key: ${{ runner.os }}-dib-${{ hashFiles('VERSION') }}
          restore-keys: ${{ runner.os }}-dib-
      - name: build the image
        run: |
          disk-image-create \
          vm \
          base \
          block-device-efi \
          ubuntu \
          -a $ARCH \
          -o $OUTPUT_FILE
      - uses: actions/upload-artifact@v3
        with:
          name: ubuntu.qcow2
          path: ${{ env.OUTPUT_FILE }}
